version: '3.9'

services:

  js_app:
    image: zhdanovich1998/$JOB_NAME:$BUILD_NUMBER
    container_name: task6
    ports:
      - "4000:4000"
    networks:
      - admin

networks:
  admin:
    driver: bridge
