version: '3.9'

services:

  js_app:
    image: zhdanovich1998/$JOB_NAME:$BUILD_NUMBER
    container_name: task6
    ports:
      - "4000:4000"
    volumes:
      - ./run.sh:/usr/run.sh
    command: ["sh","./run.sh"]

  postgres:
    image: postgres:14
    container_name: postgres-uniq
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: DB
